swagger:
    resourcePackage: mustang
server:
  applicationConnectors:
  - type: http
    port: 8080
  - type: https
    port: 8443
    # keytool -genkeypair -keyalg RSA -dname "CN=localhost" -keystore dwstart.keystore -keypass crimson -storepass crimson
    keyStorePath: ./dwstart.keystore
    keyStorePassword: "crimson"
    validateCerts: false
    validatePeers: false